---
- hosts: awshosts
  environment:
    PATH: "{{ ansible_env.PATH }}:/usr/local/go/bin"
  tasks:
    - name: "kubeadm init"
      command: "kubeadm init --pod-network-cidr=10.244.0.0/16 --cri-socket=/var/run/crio/crio.sock"
    - name: make kube homedir
      command: mkdir /root/.kube
    - name: copy kubeconfig to home
      command: cp -i /etc/kubernetes/admin.conf /root/.kube/config
    - name: chown kubefiles
      command: 'chown root:root /root/.kube/config'
    - name: install flannel
      command: 'kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml'
    - name: allow masters to run workloads
      command: 'kubectl taint nodes --all node-role.kubernetes.io/master-'
